package com.webservice.service.weather1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-13T09:33:41.254+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://inter.sei.service.webservice.com/", name = "WeatherSeiInter1")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherSeiInter1 {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://inter.sei.service.webservice.com/", className = "com.webservice.service.weather1.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://inter.sei.service.webservice.com/", className = "com.webservice.service.weather1.QueryWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
