package com.webservice.service.weather2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-12T17:50:02.500+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "WeatherSeiInter2Service", 
                  wsdlLocation = "http://127.0.0.1:12346/weather?wsdl",
                  targetNamespace = "http://inter.sei.service.webservice.com/") 
public class WeatherSeiInter2Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inter.sei.service.webservice.com/", "WeatherSeiInter2Service");
    public final static QName WeatherSeiInter2Port = new QName("http://inter.sei.service.webservice.com/", "WeatherSeiInter2Port");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:12346/weather?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherSeiInter2Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:12346/weather?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WeatherSeiInter2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherSeiInter2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherSeiInter2Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherSeiInter2Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherSeiInter2Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherSeiInter2Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WeatherSeiInter2
     */
    @WebEndpoint(name = "WeatherSeiInter2Port")
    public WeatherSeiInter2 getWeatherSeiInter2Port() {
        return super.getPort(WeatherSeiInter2Port, WeatherSeiInter2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherSeiInter2
     */
    @WebEndpoint(name = "WeatherSeiInter2Port")
    public WeatherSeiInter2 getWeatherSeiInter2Port(WebServiceFeature... features) {
        return super.getPort(WeatherSeiInter2Port, WeatherSeiInter2.class, features);
    }

}
